version: '3.8'

services:

  db:
    container_name: database
    image: postgres:12.0-alpine
    env_file: ../.env.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports: 
      - 5432:5432

  api:
    build: 
      context: ../app-backend/
      dockerfile: Dockerfile
    volumes:
      - ../app-backend/:/usr/src/app/
      - static:/src/app/static
      - static:/src/app/media           
    ports:
      - 8000:8000
    env_file:
      - ../app-backend/.env
    depends_on:
      - db
  
  react:
    container_name: react
    build:
      context: ../app-frontend/
      dockerfile: Dockerfile
    #volumes:
      #- '.:/app'
      #- '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api

volumes:
  postgres_data:
  static:
  media:
