apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: <account-id>.dkr.ecr.us-west-2.amazonaws.com/api:latest
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: api-env
        volumeMounts:
        - name: static-volume
          mountPath: /usr/src/app/static
        - name: media-volume
          mountPath: /usr/src/app/media
      volumes:
      - name: static-volume
        persistentVolumeClaim:
          claimName: static-pvc
      - name: media-volume
        persistentVolumeClaim:
          claimName: media-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
